name: imse
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - absl-py==2.3.1
      - audioread==3.0.1
      - cachetools==5.5.2
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - decorator==5.2.1
      - einops==0.6.0
      - filelock==3.16.1
      - fsspec==2025.3.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.70.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.1.0
      - librosa==0.8.1
      - llvmlite==0.39.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - natsort==8.3.0
      - networkx==3.1
      - numba==0.56.4
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - packaging==25.0
      - pesq==0.0.4
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - protobuf==3.20.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - pystoi==0.4.1
      - pyyaml==6.0.3
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rich==14.2.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.1.3
      - scipy==1.5.0
      - soundfile==0.10.3.post1
      - sympy==1.13.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.5.0
      - timm==1.0.22
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - triton==3.0.0
      - typing==3.7.4.3
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - zipp==3.20.2